### PR TITLE
added intel support for emacs-app-pretest

### PR DESCRIPTION
**Pull request by stask**
I'm pretty sure it's not the correct way to do it (changing the `.rb` file directly instead of using the template), but i'm not sure what the correct way is.

### CODE REVIEW

**Comment by maikol-solis** [comment]
Yes, please add this option.

**Comment by stask** [comment]
@maikol-solis this PR works, i just didn't build it from the template. But i had to untap `jimeh/emacs-builds` to be able to install it.

**Comment by jimeh** [comment]
Thank you for this PR and for pointing out the issue to me. This is now resolved in the `main` branch.

For the sake simplicity, rather than double checking your changes here by hand and merging them, I opted to revert the problematic commit and re-run the update GitHub Actions workflows and let them just do their thing as they usually do.

After the fact though, I can easily see your changes were exact down to every byte. So thank you again :)

The cause for the intel build missing was that the latest pretest build ran into some errors and weirdness, which caused the cask to be improperly updated when there were only assets available for ARM in the GitHub Release. And follow up cask update runs didn't notice the difference in assets, as the primary "needs update" check is based purely on the version string, which was already up to date.

**Comment by stask** [comment]
awesome, thanks @jimeh

**Pull request closed without merging**
